import Head from "next/head";
import Link from "next/link";

const Home = () => {

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <title>Salão | Home</title>
      </Head>


      <section className="h-[90vh] image-bg">

        <div className="h-[100%]">
          <div className=" box-card">
            <div className="card bg-[#87888ac5]" >
              <h3>titulo</h3>
              <p>paragrafo paragrafo paragrafo paragrafo paragrafo paragrafo</p>
              <a href="">Saiba mais</a>
            </div>
            <div className="card bg-[#87888ac5]" >
              <h3>titulo</h3>
              <p>paragrafo paragrafo paragrafo paragrafo paragrafo paragrafo</p>
              <a href="">Saiba mais</a>
            </div>
            <div className="card bg-[#87888ac5]" ><h3>titulo</h3>
              <p>paragrafo paragrafo paragrafo paragrafo paragrafo paragrafo</p>
              <a href="">Saiba mais</a>
            </div>
          </div>
        </div>

      </section>

      <section className="INFORMATIVO">
        <div className="MAX-CONTAINER">
          <div className="m-auto my-20 text-center ">

            <h2 className="text-[2.2rem] my-[2rem]">SubTitulo</h2>

            <div className="box-card bg-slate-400">
              <div className="card-informativo">
                <div className="bg-black h-16 w-16">
                  <img src="" alt="" title="" />
                </div>
                <h4>Titulo</h4>

                <p>paragrafo paragrafo paragrafo paragrafo </p>
                <Link href="/sobre">Saiba mais</Link>
              </div>

              <div className="card-informativo ">
                <div className="bg-black h-16 w-16"><img src="" alt="" title="" /></div>
                <h4>Titulo</h4>
                <p>paragrafo paragrafo paragrafo paragrafo</p>
                <Link href="/especialidades">Saiba mais</Link>
              </div>

            </div>
          </div>
        </div>
      </section>

      <section >
        <div className="MAX-CONTAINER">
          <Link href='/agendamento'>Agendar consulta</Link>
        </div>
      </section>
    </>
  );
}



export default Home