import Head from "next/head";
import Link from "next/link";
import Slider from "@/components/Slider/Slider";

const Home = () => {



  const slides = [
    'https://s1.1zoom.me/b5050/766/Gray_background_Brown_haired_Hair_Glance_Beautiful_554680_2560x1440.jpg',
    'https://s1.1zoom.me/b4142/226/Brown_haired_Hair_Glance_Face_562193_2560x1440.jpg',
    'https://th.bing.com/th/id/R.b8ba90ab11c88bdb67568ebe404dd1d2?rik=uqt3IMjO8M%2bfHA&pid=ImgRaw&r=0'
  ]
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <title>Salão - Página principal</title>
      </Head>


      <section className="relative">


        <Slider autoSlide={true} autoSlideInterval={10000}>
          {slides.map((s) => (
            <img src={s} className="object-contain " />
          ))}
        </Slider>



      </section>

      <section className="INFORMATIVO">
        <div className="MAX-CONTAINER">
          <div className="m-auto my-20 text-center ">

            <h2 className="text-[2.2rem] my-[2rem]">SubTitulo</h2>

            <div className="box-card bg-slate-400">
              <div className="card-informativo">
                <div className="bg-black h-16 w-16">
                  <img src="" alt="" title="" />
                </div>
                <h4>Titulo</h4>

                <p>paragrafo paragrafo paragrafo paragrafo </p>
                <Link href="/sobre">Saiba mais</Link>
              </div>

              <div className="card-informativo ">
                <div className="bg-black h-16 w-16"><img src="" alt="" title="" /></div>
                <h4>Titulo</h4>
                <p>paragrafo paragrafo paragrafo paragrafo</p>
                <Link href="/especialidades">Saiba mais</Link>
              </div>

            </div>
          </div>
        </div>
      </section>

      <section >
        <div className="MAX-CONTAINER">
          <Link href='/booking'>Agendar consulta</Link>
        </div>
      </section>
    </>
  );
}



export default Home